#
#  Описание: основной конфигурационный файл
#

#--- Основыне настройки сервера ---
Server:
 Name: 'web_server.ru'                                 #доменное имя виртуального хоста

 #--- Настройка сетевого соединения ---
 Connection:
  ip_version: '4'                                      #версия ip аддреса ( ip_v4 или ip_v6 )
  ip_address: '127.0.0.1'                              #ip адресс
  listen: '8888'                                       #порт

 #--- Основные директрии сервера ---
 Directories:
  document_root: '/var/www/web_server'                 #корневая директория

 #--- Настрйоки лог файлов ---
 Logs:
  error_log: '/home/roman/work/C++ /web_server/log/error.log'           #директрия до файла ошибок
  access_log: '/home/roman/work/C++ /web_server/log/access.log'         #директрия для файла выолненных действий

